from setuptools import setup, find_packages

setup(
    name="align_test",
    version="0.2.0",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    include_package_data=True,
    install_requires=[
        "pandas",
        "numpy",
        "scikit-learn",
        "transformers",
        "torch",
        "gensim",
        "nltk",
        "tqdm",
        "spacy",
        "python-dotenv",
    ],
    author="Nicholas Duran",
    author_email="nduran4@asu.edu",
    description="A package for linguistic alignment analysis in conversational data",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/nickduran/llm-linguistic-alignment",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Text Processing :: Linguistic",
    ],
    python_requires=">=3.7",
)